runtime: python312
default_expiration: "0s"

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /tests
  static_dir: tests

- url: /(manifest\.json|sw\.js)
  static_files: \1
  upload: (manifest\.json|sw\.js)

- url: /(.+)
  static_files: \1
  upload: (.+)

- url: /
  static_files: index.html
  upload: index.html
